package ua.com.internet_shop.validation;

public interface UserValidationMasages {
	
	String EMPTY_LOGIN_FIELD = "EMPTY_LOGIN_FIELD";
	String EMPTY_EMAIL_FIELD = "EMPTY_EMAIL_FIELD";
	String EMPTY_PASSWORD_FIELD = "EMPTY_PASSWORD_FIELD";
	String EMPTY_NAME_FIELD = "EMPTY_NAME_FIELD";
	String EMPTY_SURNAME_FIELD = "EMPTY_SURNAME_FIELD";
	String EMPTY_CITY_FIELD = "EMPTY_CITY_FIELD";
	String EMPTY_ADDRESS_FIELD = "EMPTY_ADDRESS_FIELD";
	String EMPTY_PHONE_FIELD = "EMPTY_PHONE_FIELD";
	String LOGIN_ALREADY_EXIST = "LOGIN_ALREADY_EXIST";

	String INCORECT_LOGIN_OR_PASSWORD = "INCORECT_LOGIN_OR_PASSWORD";
	

}
